apiVersion: v2
name: netbird
description: Self-hosted NetBird mesh VPN — management, signal, relay, and dashboard.
type: application
version: 0.3.8
# renovate: datasource=docker depName=netbirdio/management versioning=docker
appVersion: '0.74.6'
dependencies:
  - name: netbird-operator
    alias: operator
    version: 0.7.0
    repository: oci://ghcr.io/netbirdio/helm-charts
    condition: operator.enabled
