{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird.management.fullname" . }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- $secretName := include "netbird.management.fullname" . -}}
  {{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
  {{- $encKey := "" -}}
  {{- $relaySecret := "" -}}
  {{- $turnSecret := "" -}}
  {{- if $existing -}}
    {{- $encKey = index $existing.data "NB_DATASTORE_ENC_KEY" | default (randBytes 32 | b64enc) -}}
    {{- $relaySecret = index $existing.data "NB_RELAY_SECRET" | default (randBytes 32 | b64enc) -}}
    {{- $turnSecret = index $existing.data "NB_TURN_SECRET" | default (randBytes 32 | b64enc) -}}
  {{- else -}}
    {{- $encKey = randBytes 32 | b64enc -}}
    {{- $relaySecret = randBytes 32 | b64enc -}}
    {{- $turnSecret = randBytes 32 | b64enc -}}
  {{- end }}
  NB_DATASTORE_ENC_KEY: {{ $encKey | quote }}
  NB_RELAY_SECRET: {{ $relaySecret | quote }}
  NB_TURN_SECRET: {{ $turnSecret | quote }}
  NB_IDP_CLIENT_SECRET: {{ "" | b64enc | quote }}
  NB_PKCE_CLIENT_SECRET: {{ "" | b64enc | quote }}
  {{- if eq .Values.store.engine "postgres" }}
  NB_STORE_ENGINE_POSTGRES_DSN: {{ .Values.store.postgres.dsn | b64enc | quote }}
  {{- else if eq .Values.store.engine "mysql" }}
  NB_STORE_ENGINE_MYSQL_DSN: {{ .Values.store.mysql.dsn | b64enc | quote }}
  {{- end }}
  {{- if and (eq .Values.auth.mode "embedded") (eq .Values.auth.embedded.storage.type "postgres") }}
  NB_DEX_STORE_DSN: {{ .Values.auth.embedded.storage.dsn | b64enc | quote }}
  {{- end }}
{{- end }}
