{{- if and .Values.operator.enabled .Values.patSeed.enabled .Values.patSeed.writeOperatorApiKey -}}
{{- $secretName := .Values.operator.netbirdAPI.keyFromSecret.name -}}
{{- $dataKey := .Values.operator.netbirdAPI.keyFromSecret.key -}}
{{- $patSecretName := printf "%s-pat" (include "netbird.fullname" .) -}}
{{- $existing := (lookup "v1" "Secret" .Release.Namespace $secretName) -}}
{{- $apiKey := "" -}}
{{- if $existing -}}
  {{- $apiKey = index $existing.data $dataKey | default "" -}}
{{- else -}}
  {{- $patSecret := (lookup "v1" "Secret" .Release.Namespace $patSecretName) -}}
  {{- if $patSecret -}}
    {{- $apiKey = index $patSecret.data "token" | default "" -}}
  {{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "netbird.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{ $dataKey }}: {{ $apiKey | quote }}
{{- end }}
