operator:
  enabled: false
patSeed:
  enabled: false
auth:
  mode: embedded
global:
  host: 'netbird.ci.local'
relay:
  exposedAddress: 'relay.ci.local:443'
  stun:
    service:
      type: NodePort
management:
  persistence:
    enabled: false
